apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: verigate-validator
  annotations:
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 80
      containers:
        - image: us-central1-docker.pkg.dev/quick-catcher-470218-b0/cloud-run-source-deploy/verigate-validator
          resources:
            limits:
              memory: 256Mi
          env:
            - name: VALIDATOR_WALLET_ADDRESS
              value: "0xbe1424b7bcc149523f749ceb7a8316d8ba6ba558"
